version: '3'

services:
  web:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "opus.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/opus'
    ports:
      '8000:8000'